name: Creating issue on failure of a job

on: workflow_dispatch

jobs:
  fail_job_to_create_issue_demo:
    runs-on: ubuntu-latest
    steps:
      - name: first job step to pass and show some default variables
        run: |
          echo ${{ github.repository }}
          echo ${{ github.run_id }}
          echo ${{ github.workflow }}

      - name: The job step which is going to fail
        run: exit 1

      - name: The job step to create issue when on basis on previous step
        if: ${{ failure() }}
        uses: ManojCSE17/open-issue@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: found a bug
          body: bug found
          assignees: |
            purvakoushik