name: Creating issue on failure of a job

on: workflow_dispatch

jobs:
  fail_job_to_create_issue_demo:
    runs-on: ubuntu-latest
    steps:
      - name: load the code to runner
        uses: actions/checkout@v3

      - name: first job step to pass and show some default variables
        run: |
          echo ${{ github.repository }}
          echo ${{ github.run_id }}
          echo ${{ github.workflow }}

      - name: The job step to create an issue
        run: |
          curl -X POST -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" \
          -H "Content-Type: application/json" \
          -d "{\"title\":\"bug\",\"body\":\"found a bug\"}" \
          "https://api.github.com/repos/purvakoushik/testing-workflows/issues"
